from __future__ import annotations
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator

from agents.shared.state.provenance import DBProvenance


class PRSResult(BaseModel):
    """
    A single PRS result for one disease or trait.

    Represents one row from patient_prs joined with prs_metadata,
    plus LLM-generated interpretation fields.

    Provenance tracks which fields came from which DB table and tool call,
    allowing any fact to be traced back to its exact source row.
    """

    # ── Identifiers ────────────────────────────────────────────────
    prs_name: str = Field(
        ...,
        description="Primary key from prs_metadata. e.g. PRS_CAD_001"
    )
    disease_name: str = Field(
        ...,
        description="Disease or trait this PRS predicts. e.g. Coronary Artery Disease"
    )

    # ── Score data — sourced from patient_prs ──────────────────────
    prs_score: float = Field(
        ...,
        description="Raw PRS score value for this patient."
    )
    percentile: Optional[int] = Field(
        None,
        ge=0,
        le=100,
        description="Patient's percentile vs reference population (0-100)."
    )

    # ── Metadata — sourced from prs_annotations ─────────────────────────────
    source: Optional[str] = Field(
        None,
        description="Origin of PRS weights e.g. PGS Catalog PGS000013."
    )
    metadata_notes: Optional[str] = Field(
        None,
        description="Any caveats or notes from prs_annotations."
    )

    # ── LLM-generated — explicitly no DB provenance ───────────────
    risk_band: Optional[str] = Field(
        None,
        description="Controlled vocab: low | average | high | very_high. "
                    "Derived from percentile by the agent."
    )
    interpretation: Optional[str] = Field(
        None,
        description="Human-readable explanation of what this score means "
                    "for the patient. Generated by LLM."
    )
    interpretation_model: Optional[str] = Field(
        None,
        description="Which LLM generated the interpretation. "
                    "e.g. claude-sonnet-4-20250514"
    )

    # ── Provenance — one entry per source table touched ───────────
    provenance: List[DBProvenance] = Field(
        default_factory=list,
        description=(
            "One provenance record per DB table touched to build this result. "
            "Typically two entries: one for patient_prs, one for prs_metadata. "
            "LLM-generated fields (risk_band, interpretation) have no provenance entry."
        )
    )

    @field_validator("risk_band")
    @classmethod
    def validate_risk_band(cls, v: Optional[str]) -> Optional[str]:
        allowed = {"low", "average", "high", "very_high"}
        if v is not None and v not in allowed:
            raise ValueError(f"risk_band must be one of {allowed}, got '{v}'")
        return v


class PRSResultList(BaseModel):
    """
    The full set of PRS results for a patient.
    Top-level output schema of the PRS agent.
    """
    results: List[PRSResult] = Field(
        default_factory=list,
        description="One PRSResult per disease/trait scored for this patient."
    )
    summary: Optional[str] = Field(
        None,
        description=(
            "Cross-PRS narrative generated by the agent. Should highlight "
            "patterns across traits e.g. elevated polygenic risk across "
            "multiple cardiovascular conditions."
        )
    )
    summary_model: Optional[str] = Field(
        None,
        description="Which LLM generated the summary."
    )


class PRSKey(BaseModel):
    """
    Minimal patient-scoped PRS key returned by explore_patient_prs.
    Contains just enough to orient the agent before annotation and retrieval.
    """
    prs_name: str = Field(..., description="PRS identifier from patient_prs.")
    disease_name: str = Field(..., description="Disease this score covers.")
    risk_band: Optional[str] = Field(None, description="Risk band stored in patient_prs.")