-- =============================================================================
-- EGP Window — Baseline Postgres schema (V001)
--
-- Port of the LangGraph prototype's DuckDB schema at test_data/schema.sql.
--
-- Deviations from the prototype (Design §11.2), all mechanical:
--   - JSON  → jsonb
--   - INTEGER DEFAULT nextval('seq') PRIMARY KEY  → INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   - CREATE SEQUENCE ... START 1  removed (identity columns replace them)
--   - patient_id declared NOT NULL on composite-PK tables (was implicit in DuckDB)
--   - VARCHAR without length → text (idiomatic Postgres; behaviour identical)
--
-- The intent is byte-parity of *content*: same tables, same columns, same
-- constraints, same indexes, same CHECK vocabularies.
--
-- This file is executed by the Alembic upgrade at revision 001_baseline_schema.
-- It is idempotent-safe only via IF NOT EXISTS on some CREATE INDEX statements;
-- CREATE TABLE is NOT idempotent — Alembic guarantees single-application.
-- =============================================================================


-- =============================================================================
-- PATIENTS
-- Root identity table. patient_id is the shared FK across all clinical tables.
-- =============================================================================

CREATE TABLE patients (
    patient_id              text PRIMARY KEY,
    medical_record_number   text,
    date_of_birth           date NOT NULL,
    sex                     text,
    created_date            date,
    last_updated            date,
    CHECK (sex IN ('female', 'male', 'other', 'unknown'))
);

CREATE INDEX idx_patients_mrn ON patients(medical_record_number);


-- =============================================================================
-- DIAGNOSES / PHENOTYPE
-- One row per diagnosis encounter. Feeds the phenotype specialist.
-- =============================================================================

CREATE TABLE diagnoses (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      text    NOT NULL,
    code            text    NOT NULL,
    code_type       text    NOT NULL,
    term            text    NOT NULL,
    description     text,
    disease_name    text,
    encounter_date  date,
    recorded_date   date,
    visit_id        text,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    UNIQUE (patient_id, code, encounter_date),
    CHECK (code_type IN ('ICD10', 'ICD9', 'SNOMED', 'HPO', 'OMIM', 'MONDO', 'OTHER'))
);

CREATE INDEX idx_diagnoses_patient         ON diagnoses(patient_id);
CREATE INDEX idx_diagnoses_code            ON diagnoses(code);
CREATE INDEX idx_diagnoses_date            ON diagnoses(encounter_date);
CREATE INDEX idx_diagnoses_code_type       ON diagnoses(code_type);
CREATE INDEX idx_diagnoses_disease         ON diagnoses(disease_name);
CREATE INDEX idx_diagnoses_patient_disease ON diagnoses(patient_id, disease_name);


-- =============================================================================
-- PRS
-- prs_annotations = reference (source, notes). patient_prs = patient scores.
-- patient_prs.disease_name is intentionally denormalised (Design §6.4).
-- =============================================================================

CREATE TABLE prs_annotations (
    prs_name        text PRIMARY KEY,
    disease_name    text NOT NULL,
    source          text,
    notes           text,
    last_updated    date
);

CREATE INDEX idx_prs_annotations_disease ON prs_annotations(disease_name);

CREATE TABLE patient_prs (
    patient_id      text NOT NULL,
    prs_name        text NOT NULL,
    disease_name    text NOT NULL,
    prs_score       double precision NOT NULL,
    percentile      integer,
    risk_band       text,
    prs_tool        text,
    computed_date   date,
    last_updated    date,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (prs_name)   REFERENCES prs_annotations(prs_name),
    CHECK (percentile BETWEEN 0 AND 100),
    CHECK (risk_band IN ('low', 'average', 'high', 'very_high')),
    PRIMARY KEY (patient_id, prs_name)
);

CREATE INDEX idx_patient_prs_disease   ON patient_prs(disease_name);
CREATE INDEX idx_patient_prs_name      ON patient_prs(prs_name);
CREATE INDEX idx_patient_prs_risk_band ON patient_prs(risk_band);


-- =============================================================================
-- GENOMIC VARIANTS
-- variant_annotations = reference (per-variant catalog).
-- patient_variants   = patient sample-level detail.
-- annotations_json is jsonb — evolvable annotations (HGVS, gnomAD, ACMG, ...).
-- =============================================================================

CREATE TABLE variant_annotations (
    variant_id              text PRIMARY KEY,
    gene                    text NOT NULL,
    variant_type            text,
    pathogenicity           text,
    pathogenicity_source    text,
    disease_name            text,
    inheritance             text,
    notes                   text,
    annotations_json        jsonb,
    created_date            date,
    last_updated            date,
    CHECK (pathogenicity IN (
        'Pathogenic',
        'Likely Pathogenic',
        'Variant of Uncertain Significance',
        'Likely Benign',
        'Benign',
        'Unknown'
    )),
    CHECK (inheritance IN (
        'Autosomal Dominant',
        'Autosomal Recessive',
        'X-Linked',
        'Y-Linked',
        'Complex',
        'Mitochondrial',
        'Unknown'
    ))
);

CREATE INDEX idx_variant_annotations_gene          ON variant_annotations(gene);
CREATE INDEX idx_variant_annotations_disease       ON variant_annotations(disease_name);
CREATE INDEX idx_variant_annotations_pathogenicity ON variant_annotations(pathogenicity);
CREATE INDEX idx_variant_annotations_gene_path     ON variant_annotations(gene, pathogenicity);

CREATE TABLE patient_variants (
    patient_id          text NOT NULL,
    variant_id          text NOT NULL,
    genotype            text,
    zygosity            text,
    sequencing_platform text,
    variant_caller      text,
    call_quality        double precision,
    computed_date       date,
    last_updated        date,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (variant_id) REFERENCES variant_annotations(variant_id),
    PRIMARY KEY (patient_id, variant_id)
);

CREATE INDEX idx_patient_variants_variant ON patient_variants(variant_id);


-- =============================================================================
-- PGX
-- patient_pgx_status = diplotype + phenotype per gene for a patient.
-- pgx_annotations    = CPIC-sourced drug recommendations keyed on
--                      (gene, phenotype, drug).
-- =============================================================================

CREATE TABLE patient_pgx_status (
    patient_id      text NOT NULL,
    gene            text NOT NULL,
    diplotype       text,
    phenotype       text,
    pgx_tool        text,
    computed_date   date,
    last_updated    date,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    PRIMARY KEY (patient_id, gene),
    CHECK (phenotype IN (
        'Poor Metabolizer',
        'Intermediate Metabolizer',
        'Normal Metabolizer',
        'Rapid Metabolizer',
        'Unknown'
    ))
);

CREATE INDEX idx_patient_pgx_gene ON patient_pgx_status(gene);

CREATE TABLE pgx_annotations (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gene                    text NOT NULL,
    phenotype               text NOT NULL,
    drug                    text NOT NULL,
    recommendation          text,
    summary                 text,
    source                  text,
    created_date            date,
    last_updated            date,
    CHECK (phenotype IN (
        'Poor Metabolizer',
        'Intermediate Metabolizer',
        'Normal Metabolizer',
        'Rapid Metabolizer',
        'Unknown'
    )),
    UNIQUE (gene, phenotype, drug)
);

CREATE INDEX idx_pgx_annotations_lookup    ON pgx_annotations(gene, phenotype);
CREATE INDEX idx_pgx_annotations_gene      ON pgx_annotations(gene);
CREATE INDEX idx_pgx_annotations_drug      ON pgx_annotations(drug);
CREATE INDEX idx_pgx_annotations_drug_gene ON pgx_annotations(drug, gene);


-- =============================================================================
-- FAMILY HISTORY
-- kinship_history_annotations first — patient_kinship_history has a composite
-- FK to it, so it must be created after.
-- =============================================================================

CREATE TABLE kinship_history_annotations (
    disease_name    text NOT NULL,
    criteria_name   text NOT NULL,
    description     text,
    source          text,
    created_date    date,
    last_updated    date,
    PRIMARY KEY (disease_name, criteria_name)
);

CREATE TABLE patient_kinship_history (
    patient_id                          text    NOT NULL,
    disease_name                        text    NOT NULL,
    criteria_name                       text    NOT NULL,
    affected_relative_count             integer,
    total_relatives_searched            integer,
    search_context_notes                text,
    last_observed_diagnosis_in_database date,
    meets_threshold                     boolean NOT NULL,
    computed_date                       date,
    last_updated                        date,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (disease_name, criteria_name)
        REFERENCES kinship_history_annotations(disease_name, criteria_name),
    PRIMARY KEY (patient_id, disease_name, criteria_name)
);

CREATE INDEX idx_kinship_patient         ON patient_kinship_history(patient_id);
CREATE INDEX idx_kinship_disease         ON patient_kinship_history(disease_name);
CREATE INDEX idx_kinship_criteria        ON patient_kinship_history(criteria_name);
CREATE INDEX idx_kinship_meets_threshold ON patient_kinship_history(meets_threshold);


-- =============================================================================
-- Grant SELECT on all new tables to the read-only application role.
-- Deployment note (Design §11.5): egp_agent_ro is granted SELECT via ALTER
-- DEFAULT PRIVILEGES set up in bootstrap/roles.sql. This explicit block is a
-- belt-and-braces guarantee for tables created before the default privileges
-- were in place.
-- =============================================================================

GRANT SELECT ON ALL TABLES IN SCHEMA public TO egp_agent_ro;
GRANT USAGE  ON ALL SEQUENCES IN SCHEMA public TO egp_agent_ro;
